//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayordomoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celulas
    {
        public System.Guid IdCelula { get; set; }
        public string Nombre { get; set; }
        public string Address { get; set; }
        public string NombrePersona { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
